#!/usr/bin/with-contenv bash

STAGE="[init-stage2]"

echo "${STAGE} processing init-stage2..."

# Directories
SCRIPTS_DIR="/etc/cont-init.d"
SERVICES_DIR="/config/repository.services.d"

# Remove all existing custom services before continuing to ensure
# we aren't running anything the user may have removed
if [ -n "$(/bin/ls -A /etc/services.d/custom-service-* 2>/dev/null)" ]; then
  echo "[custom-init] removing existing custom services..."
  rm -rf /etc/services.d/custom-service-*
fi

# Make sure custom init directory exists and has files in it
if ([ -e "${SCRIPTS_DIR}" ] && [ -n "$(/bin/ls -A ${SCRIPTS_DIR} 2>/dev/null)" ]) || ([ -e "${SERVICES_DIR}" ] && [ -n "$(/bin/ls -A ${SERVICES_DIR} 2>/dev/null)" ]); then
  if [ -n "$(/bin/ls -A ${SCRIPTS_DIR} 2>/dev/null)" ]; then
    echo "${STAGE} script files found in ${SCRIPTS_DIR} executing..."

    for SCRIPT in ${SCRIPTS_DIR}/*; do
      NAME="$(basename "${SCRIPT}")"

      if [ -f "${SCRIPT}" ]; then
        echo "${STAGE} ${NAME}: executing..."
        /bin/bash ${SCRIPT}
        echo "${STAGE} ${NAME}: exited $?"
      elif [ ! -f "${SCRIPT}" ]; then
        echo "${STAGE} ${NAME}: is not a file"
      fi
    done
  fi
  if [ -n "$(/bin/ls -A ${SERVICES_DIR} 2>/dev/null)" ]; then
    echo "${STAGE}  service files found in ${SERVICES_DIR}"

    for SERVICE in ${SERVICES_DIR}/*; do
      NAME="$(basename "${SERVICE}")"

      if [ -f "${SERVICE}" ]; then
        echo "${STAGE} ${NAME}: service detected, copying..."
        mkdir -p /etc/services.d/custom-service-${NAME} /var/run/s6/services/custom-service-${NAME}/{event,supervise}
        echo "${STAGE} ${NAME}: directories created"
        chmod 03730 /var/run/s6/services/custom-service-${NAME}/event
        chmod 700 /var/run/s6/services/custom-service-${NAME}/supervise
        echo "${STAGE} ${NAME}: directory permissions set"
        cp ${SERVICE} /etc/services.d/custom-service.d-${NAME}/
        mv /etc/services.d/custom-services.d-${NAME}/${NAME} /etc/services.d/custom-service-${NAME}/run
        echo "${STAGE} ${NAME}: service moved to service.d"
        chmod 755 /etc/services.d/custom-service-${NAME}/run
        echo "${STAGE} ${NAME}: service permissions set"
        ln -s /etc/services.d/custom-service-${NAME}/run /var/run/s6/services/custom-service-${NAME}/run
        echo "${STAGE} ${NAME}: service linked"
      elif [ ! -f "${SERVICE}" ]; then
        echo "${STAGE} ${NAME}: is not a file"
      fi
    done

    s6-svscanctl -a /var/run/s6/services
    if [ $? ]; then
      echo "${STAGE} services started"
    else
      echo "${STAGE} services failed"
    fi
  fi
else
  echo "${STAGE} no custom files found exiting..."
  s6-svscanctl -a /var/run/s6/services
  if [ $? ]; then
    echo "${STAGE} services started"
  else
    echo "${STAGE} services failed"
  fi
fi
